<a href="https://colab.research.google.com/github/Nemit-jindal/ML_Model_Training_Pipeline_ColumnTransform/blob/main/Model_Training_Pipeline_ColumnTransform.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [25]:
df=sns.load_dataset("tips")
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [26]:
df.time.unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [27]:
#EDA
#Encoding,Scaling,Missing value treatment
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df['time']=encoder.fit_transform(df["time"])
df

total_bill   tip     sex smoker   day  time  size
0         16.99  1.01  Female     No   Sun     0     2
1         10.34  1.66    Male     No   Sun     0     3
2         21.01  3.50    Male     No   Sun     0     3
3         23.68  3.31    Male     No   Sun     0     2
4         24.59  3.61  Female     No   Sun     0     4
..          ...   ...     ...    ...   ...   ...   ...
239       29.03  5.92    Male     No   Sat     0     3
240       27.18  2.00  Female    Yes   Sat     0     2
241       22.67  2.00    Male    Yes   Sat     0     2
242       17.82  1.75    Male     No   Sat     0     2
243       18.78  3.00  Female     No  Thur     0     2

[244 rows x 7 columns]

In [28]:
# aim--> to predict time
df.time.unique()# dinner-->0 lunch-->1

array([0, 1])

In [29]:
x=df.drop('time',axis=1)
y=df['time']

In [30]:
x

total_bill   tip     sex smoker   day  size
0         16.99  1.01  Female     No   Sun     2
1         10.34  1.66    Male     No   Sun     3
2         21.01  3.50    Male     No   Sun     3
3         23.68  3.31    Male     No   Sun     2
4         24.59  3.61  Female     No   Sun     4
..          ...   ...     ...    ...   ...   ...
239       29.03  5.92    Male     No   Sat     3
240       27.18  2.00  Female    Yes   Sat     2
241       22.67  2.00    Male    Yes   Sat     2
242       17.82  1.75    Male     No   Sat     2
243       18.78  3.00  Female     No  Thur     2

[244 rows x 6 columns]

In [31]:
y

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    0
241    0
242    0
243    0
Name: time, Length: 244, dtype: int64

In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=1)

In [33]:
x_train

total_bill   tip     sex smoker   day  size
0         16.99  1.01  Female     No   Sun     2
154       19.77  2.00    Male     No   Sun     4
167       31.71  4.50    Male     No   Sun     4
110       14.00  3.00    Male     No   Sat     2
225       16.27  2.50  Female    Yes   Fri     2
..          ...   ...     ...    ...   ...   ...
137       14.15  2.00  Female     No  Thur     2
72        26.86  3.14  Female    Yes   Sat     2
140       17.47  3.50  Female     No  Thur     2
235       10.07  1.25    Male     No   Sat     2
37        16.93  3.07  Female     No   Sat     3

[195 rows x 6 columns]

In [34]:
x_test

total_bill    tip     sex smoker   day  size
67         3.07   1.00  Female    Yes   Sat     1
243       18.78   3.00  Female     No  Thur     2
206       26.59   3.41    Male    Yes   Sat     3
122       14.26   2.50    Male     No  Thur     2
89        21.16   3.00    Male     No  Thur     2
218        7.74   1.44    Male    Yes   Sat     2
58        11.24   1.76    Male    Yes   Sat     2
186       20.90   3.50  Female    Yes   Sun     3
177       14.48   2.00    Male    Yes   Sun     2
4         24.59   3.61  Female     No   Sun     4
220       12.16   2.20    Male    Yes   Fri     2
226       10.09   2.00  Female    Yes   Fri     2
116       29.93   5.07    Male     No   Sun     4
107       25.21   4.29    Male    Yes   Sat     2
170       50.81  10.00    Male    Yes   Sat     3
241       22.67   2.00    Male    Yes   Sat     2
181       23.33   5.65    Male    Yes   Sun     2
51        10.29   2.60  Female     No   Sun     2
27        12.69   2.00    Male     No   Sat     2
240       27.18   2.00  Female    Yes   Sat     2
219       30.14   3.09  Female    Yes   Sat     4
34        17.78   3.27    Male     No   Sat     2
93        16.32   4.30  Female    Yes   Fri     2
183       23.17   6.50    Male    Yes   Sun     4
118       12.43   1.80  Female     No  Thur     2
117       10.65   1.50  Female     No  Thur     2
106       20.49   4.06    Male    Yes   Sat     2
73        25.28   5.00  Female    Yes   Sat     2
38        18.69   2.31    Male     No   Sat     3
210       30.06   2.00    Male    Yes   Sat     3
202       13.00   2.00  Female    Yes  Thur     2
44        30.40   5.60    Male     No   Sun     4
62        11.02   1.98    Male    Yes   Sat     2
238       35.83   4.67  Female     No   Sat     3
85        34.83   5.17  Female     No  Thur     4
224       13.42   1.58    Male    Yes   Fri     2
39        31.27   5.00    Male     No   Sat     3
31        18.35   2.50    Male     No   Sat     4
18        16.97   3.50  Female     No   Sun     3
132       11.17   1.50  Female     No  Thur     2
119       24.08   2.92  Female     No  Thur     4
19        20.65   3.35    Male     No   Sat     3
91        22.49   3.50    Male     No   Fri     2
69        15.01   2.09    Male    Yes   Sat     2
33        20.69   2.45  Female     No   Sat     4
90        28.97   3.00    Male    Yes   Fri     2
35        24.06   3.60    Male     No   Sat     3
11        35.26   5.00  Female     No   Sun     4
29        19.65   3.00  Female     No   Sat     2

In [35]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [36]:
#handling missing values
#data encoding
#feature scaling

from sklearn.impute import SimpleImputer # for missing values
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

#pipeline-->a sequence of data transformation
#column transformer--> groups all the pipeline steps for each of columns

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [37]:
df

total_bill   tip     sex smoker   day  time  size
0         16.99  1.01  Female     No   Sun     0     2
1         10.34  1.66    Male     No   Sun     0     3
2         21.01  3.50    Male     No   Sun     0     3
3         23.68  3.31    Male     No   Sun     0     2
4         24.59  3.61  Female     No   Sun     0     4
..          ...   ...     ...    ...   ...   ...   ...
239       29.03  5.92    Male     No   Sat     0     3
240       27.18  2.00  Female    Yes   Sat     0     2
241       22.67  2.00    Male    Yes   Sat     0     2
242       17.82  1.75    Male     No   Sat     0     2
243       18.78  3.00  Female     No  Thur     0     2

[244 rows x 7 columns]

In [38]:
cat_cols=["sex","smoker","day"]
num_cols=["total_bill","tip","size"]

In [39]:
#feature engineering automation using pipeline and column transformer
num_pipeline=Pipeline(steps=[('imputation',SimpleImputer(strategy="median")),('scaling',StandardScaler())])
cat_pipeline=Pipeline(steps=[('imputation',SimpleImputer(strategy="most_frequent")),('encoding',OneHotEncoder())])

In [42]:
preprocessor=ColumnTransformer([("num_pipeline",num_pipeline,num_cols),("cat_pipeline",cat_pipeline,cat_cols)])

In [43]:
x_train=preprocessor.fit_transform(x_train)
x_test=preprocessor.transform(x_test)

In [44]:
x_train

array([[-0.28611937, -1.47443803, -0.57766863, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.02695905, -0.71612531,  1.47042924, ...,  0.        ,
         1.        ,  0.        ],
       [ 1.3716196 ,  1.19880579,  1.47042924, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-0.23206267,  0.43283335, -0.57766863, ...,  0.        ,
         0.        ,  1.        ],
       [-1.06543688, -1.29060464, -0.57766863, ...,  1.        ,
         0.        ,  0.        ],
       [-0.29287646,  0.1034652 ,  0.44638031, ...,  1.        ,
         0.        ,  0.        ]])

In [45]:
x_test

array([[-1.85376383, -1.48209775, -1.60171757,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.08453291,  0.04984713, -0.57766863,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.79501474,  0.36389583,  0.44638031,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.59356688, -0.33313909, -0.57766863,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.18349826,  0.04984713, -0.57766863,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [-1.32783714, -1.14506988, -0.57766863,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.   

In [46]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

models={"SVC":SVC(),
        "dtc":DecisionTreeClassifier(),
        "Logreg":LogisticRegression()}

In [55]:
models.keys()

dict_keys(['SVC', 'dtc', 'Logreg'])

In [53]:
from sklearn.metrics import accuracy_score

def model_train_eval(x_train,x_test,y_train,y_test,models):
  evaluation={}
  for i in range(len(models)):
    model=list(models.values())[i]
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    model_score=accuracy_score(y_test,y_pred)
    evaluation[list(models.keys())[i]]=model_score
  return evaluation

In [54]:
model_train_eval(x_train,x_test,y_train,y_test,models)

{'SVC': 0.9183673469387755,
 'dtc': 0.9183673469387755,
 'Logreg': 0.9183673469387755}